-- 1. Nâng cấp Địa chính (Geography)
-- Tạo bảng Huyện
CREATE TABLE public.dm_huyen (
    ma_huyen TEXT PRIMARY KEY,
    ten_huyen TEXT NOT NULL,
    ma_tinh TEXT REFERENCES public.dm_tinh(ma_tinh)
);

-- Cập nhật bảng Xã: Thêm cột ma_huyen
ALTER TABLE public.dm_xa ADD COLUMN ma_huyen TEXT REFERENCES public.dm_huyen(ma_huyen);
-- Note: Sau này cần script để update data ma_huyen cho các xã hiện có

-- Cập nhật bảng Thí sinh: Thêm cột ma_huyen_thuong_tru
ALTER TABLE public.thi_sinh ADD COLUMN ma_huyen_thuong_tru TEXT REFERENCES public.dm_huyen(ma_huyen);


-- 2. Nâng cấp Tuyển sinh (Admissions)
-- Tạo bảng Năm tuyển sinh
CREATE TABLE public.dm_nam_tuyen_sinh (
    nam INT PRIMARY KEY,
    mo_ta TEXT,
    trang_thai TEXT DEFAULT 'Active', -- Active, Inactive
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Thêm năm 2024, 2025 mẫu
INSERT INTO public.dm_nam_tuyen_sinh (nam, mo_ta) VALUES (2024, 'Tuyển sinh Đại học 2024');
INSERT INTO public.dm_nam_tuyen_sinh (nam, mo_ta) VALUES (2025, 'Tuyển sinh Đại học 2025');

-- Cập nhật bảng Đợt tuyển sinh
ALTER TABLE public.dot_tuyen_sinh ADD COLUMN ma_dot TEXT; -- VD: Dot1, Dot2 (Slug for folder name)
ALTER TABLE public.dot_tuyen_sinh ADD COLUMN dm_nam_tuyen_sinh_nam INT REFERENCES public.dm_nam_tuyen_sinh(nam);

-- Tạo bảng Hồ sơ xét tuyển (Quản lý hồ sơ theo đợt)
CREATE TABLE public.ho_so_xet_tuyen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_cccd TEXT REFERENCES public.thi_sinh(so_cccd) ON DELETE CASCADE,
    dot_tuyen_sinh_id INT REFERENCES public.dot_tuyen_sinh(id),
    
    trang_thai TEXT DEFAULT 'Chờ duyệt', -- Chờ duyệt, Yêu cầu sửa, Đã duyệt, Trúng tuyển
    
    -- Lưu ID folder Drive của hồ sơ này để không phải search lại
    path_driver_folder TEXT, 
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Một thí sinh chỉ được nộp 1 bộ hồ sơ trong 1 đợt (nhưng có thể nộp nhiều đợt khác nhau)
    CONSTRAINT unique_hoso_dot UNIQUE (so_cccd, dot_tuyen_sinh_id)
);

-- Cập nhật bảng Nguyện vọng: Link tới Hồ sơ xét tuyển thay vì chỉ CCCD
-- (Logic cũ là link theo CCCD, logic mới là link theo Hồ sơ của đợt đó)
ALTER TABLE public.nguyen_vong ADD COLUMN ho_so_id BIGINT REFERENCES public.ho_so_xet_tuyen(id) ON DELETE CASCADE;

-- RLS Updates (Nếu dùng Supabase Auth, cần policy cho bảng mới)
ALTER TABLE public.dm_huyen ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dm_nam_tuyen_sinh ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ho_so_xet_tuyen ENABLE ROW LEVEL SECURITY;

-- Policy mẫu (Cho phép public read danh mục, auth read hồ sơ của mình)
CREATE POLICY "Public read danh mục huyện" ON public.dm_huyen FOR SELECT USING (true);
CREATE POLICY "Public read năm tuyển sinh" ON public.dm_nam_tuyen_sinh FOR SELECT USING (true);
