-- migrations/v6_homepage_and_news.sql

-- 1. Bảng Tin bài & Thông báo (Posts)
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    summary TEXT,
    content TEXT,
    thumbnail TEXT,
    category TEXT DEFAULT 'Tin tức', -- Tin tức, Thông báo, Hướng dẫn
    status TEXT DEFAULT 'Draft', -- Draft, Published
    is_featured BOOLEAN DEFAULT false,
    view_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Nâng cấp bảng Ngành tuyển sinh (dm_nganh)
-- Kiểm tra và thêm cột nếu chưa có (vì dm_nganh đã tồn tại)
ALTER TABLE public.dm_nganh ADD COLUMN IF NOT EXISTS chi_tieu INT DEFAULT 0;
ALTER TABLE public.dm_nganh ADD COLUMN IF NOT EXISTS diem_nam_truoc FLOAT DEFAULT 0;
ALTER TABLE public.dm_nganh ADD COLUMN IF NOT EXISTS ghi_chu TEXT;

-- 3. Bảng Điều kiện dự tuyển & Cấu hình (Nếu cần linh hoạt hơn văn bản tĩnh)
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT,
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Chèn dữ liệu mẫu cho bài viết
INSERT INTO public.posts (title, slug, summary, content, category, status, is_featured) VALUES 
('Thông báo Tuyển sinh Đại học Chính quy năm 2025', 'thong-bao-tuyen-sinh-2025', 'Trường Đại học Hùng Vương thông báo kế hoạch tuyển sinh năm 2025 với nhiều chuyên ngành hấp dẫn.', 'Nội dung chi tiết thông báo tuyển sinh...', 'Thông báo', 'Published', true),
('Hướng dẫn đăng ký xét tuyển trực tuyến', 'huong-dan-dang-ky-2025', 'Các bước chi tiết để thí sinh đăng ký tài khoản và nộp hồ sơ xét tuyển vào HVU.', 'Nội dung hướng dẫn...', 'Hướng dẫn', 'Published', false);

-- Chèn dữ liệu mẫu điều kiện dự tuyển
INSERT INTO public.settings (key, value, description) VALUES 
('admission_conditions', '- Tốt nghiệp THPT hoặc tương đương.\n- Hạnh kiểm xếp loại Khá trở lên.\n- Tổng điểm trung bình 3 môn tổ hợp lớp 12 >= 18.0.', 'Điều kiện dự tuyển hiển thị trên trang chủ');
