TRUNCATE TABLE public.dm_xa CASCADE;
TRUNCATE TABLE public.dm_huyen CASCADE;
TRUNCATE TABLE public.dm_tinh CASCADE;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('01', '10105001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('02', '22113001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('03', '22521001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('04', '10311001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('05', '10901001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('06', '11707001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('07', '20301001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('08', '21113001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('09', '21309001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('10', '21501001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('11', '20903001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('12', '21701001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('13', '30101001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('14', '30209001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('15', '30301001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('16', '40101001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('17', '40327001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('18', '40520001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('19', '40701001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('20', '41109001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('21', '50101001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('22', '50501001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('23', '51101001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('24', '50701001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('25', '60501001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('26', '70301001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('27', '80103001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('28', '71301001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('29', '71701001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('30', '81701037') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('31', '80701001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('32', '80501001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('33', '81519001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_tinh (ma_tinh, ten_tinh) VALUES ('34', '82301001') ON CONFLICT (ma_tinh) DO UPDATE SET ten_tinh = EXCLUDED.ten_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00101', '10105', '01') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00223', '22113', '02') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00225', '22521', '03') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00103', '10311', '04') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00109', '10901', '05') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00117', '11707', '06') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00203', '20301', '07') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00211', '21113', '08') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00205', '21309', '09') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00215', '21501', '10') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00209', '20903', '11') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00217', '21701', '12') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00301', '30101', '13') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00302', '30209', '14') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00303', '30301', '15') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00401', '40101', '16') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00403', '40327', '17') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00405', '40520', '18') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00409', '40701', '19') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00411', '41109', '20') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00501', '50101', '21') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00505', '50501', '22') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00511', '51101', '23') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00603', '50701', '24') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00605', '60501', '25') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00703', '70301', '26') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00709', '80103', '27') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00713', '71301', '28') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00701', '71701', '29') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00809', '81701', '30') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00803', '80701', '31') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00805', '80501', '32') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00815', '81519', '33') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;
INSERT INTO public.dm_xa (ma_xa, ten_xa, ma_tinh) VALUES ('00823', '82301', '34') ON CONFLICT (ma_xa) DO UPDATE SET ten_xa = EXCLUDED.ten_xa, ma_tinh = EXCLUDED.ma_tinh;