-- database/schema.sql
-- Consolidated Schema for HVU Admissions System 2025

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Master Data
CREATE TABLE dm_tinh (ma_tinh TEXT PRIMARY KEY, ten_tinh TEXT NOT NULL);
CREATE TABLE dm_huyen (ma_huyen TEXT PRIMARY KEY, ten_huyen TEXT NOT NULL, ma_tinh TEXT REFERENCES dm_tinh(ma_tinh));
CREATE TABLE dm_xa (ma_xa TEXT PRIMARY KEY, ten_xa TEXT NOT NULL, ma_huyen TEXT REFERENCES dm_huyen(ma_huyen));

CREATE TABLE dm_truong_thpt (
    ma_truong TEXT PRIMARY KEY,
    ten_truong TEXT NOT NULL,
    khu_vuc TEXT,
    ma_tinh TEXT REFERENCES dm_tinh(ma_tinh)
);

CREATE TABLE dm_nganh (
    ma_nganh TEXT PRIMARY KEY,
    ten_nganh TEXT NOT NULL,
    khoi_xet_tuyen TEXT,
    chi_tieu INT DEFAULT 0,
    diem_nam_truoc FLOAT DEFAULT 0,
    ghi_chu TEXT
);

CREATE TABLE dm_nam_tuyen_sinh (
    nam INT PRIMARY KEY,
    mo_ta TEXT,
    trang_thai TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE dot_tuyen_sinh (
    id SERIAL PRIMARY KEY,
    ten_dot TEXT NOT NULL,
    ma_dot TEXT,
    nam_tuyen_sinh INT,
    dm_nam_tuyen_sinh_nam INT REFERENCES dm_nam_tuyen_sinh(nam),
    ngay_bat_dau DATE,
    ngay_ket_thuc DATE,
    kich_hoat BOOLEAN DEFAULT true
);

-- 2. Candidates
CREATE TABLE thi_sinh (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    so_cccd TEXT UNIQUE NOT NULL,
    mat_khau TEXT,
    ho_va_ten TEXT NOT NULL,
    ngay_sinh DATE,
    gioi_tinh TEXT,
    dan_toc TEXT,
    dien_thoai TEXT,
    email TEXT,
    khu_vuc_uu_tien TEXT,
    doi_tuong_uu_tien TEXT,
    ma_tinh_thuong_tru TEXT REFERENCES dm_tinh(ma_tinh),
    ma_huyen_thuong_tru TEXT REFERENCES dm_huyen(ma_huyen),
    ma_xa_thuong_tru TEXT REFERENCES dm_xa(ma_xa),
    dia_chi_chi_tiet TEXT,
    ma_tinh_lop_12 TEXT,
    ma_truong_lop_12 TEXT REFERENCES dm_truong_thpt(ma_truong),
    nam_tot_nghiep INT,
    anh_dai_dien TEXT,
    anh_cccd_truoc TEXT,
    anh_cccd_sau TEXT,
    ngay_tao TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Admissions
CREATE TABLE ho_so_xet_tuyen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_cccd TEXT REFERENCES thi_sinh(so_cccd) ON DELETE CASCADE,
    dot_tuyen_sinh_id INT REFERENCES dot_tuyen_sinh(id),
    trang_thai TEXT DEFAULT 'Chờ duyệt',
    path_driver_folder TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_hoso_dot UNIQUE (so_cccd, dot_tuyen_sinh_id)
);

CREATE TABLE ket_qua_hoc_tap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_cccd TEXT REFERENCES thi_sinh(so_cccd) ON DELETE CASCADE,
    lop INT CHECK (lop IN (10, 11, 12)),
    nam_hoc INT,
    hoc_luc_ca_nam TEXT,
    hanh_kiem_ca_nam TEXT,
    diem_tb_ca_nam FLOAT,
    diem_toan_hk1 FLOAT, diem_toan_hk2 FLOAT, diem_toan_cn FLOAT,
    diem_van_hk1 FLOAT, diem_van_hk2 FLOAT, diem_van_cn FLOAT,
    diem_ngoai_ngu_hk1 FLOAT, diem_ngoai_ngu_hk2 FLOAT, diem_ngoai_ngu_cn FLOAT,
    diem_ly_hk1 FLOAT, diem_ly_hk2 FLOAT, diem_ly_cn FLOAT,
    diem_hoa_hk1 FLOAT, diem_hoa_hk2 FLOAT, diem_hoa_cn FLOAT,
    diem_sinh_hk1 FLOAT, diem_sinh_hk2 FLOAT, diem_sinh_cn FLOAT,
    diem_su_hk1 FLOAT, diem_su_hk2 FLOAT, diem_su_cn FLOAT,
    diem_dia_hk1 FLOAT, diem_dia_hk2 FLOAT, diem_dia_cn FLOAT,
    diem_gdcd_hk1 FLOAT, diem_gdcd_hk2 FLOAT, diem_gdcd_cn FLOAT,
    diem_tin_hoc_cn FLOAT,
    diem_cong_nghe_cn FLOAT,
    file_hoc_ba TEXT,
    file_bang_tot_nghiep TEXT
);

CREATE TABLE nguyen_vong (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_cccd TEXT REFERENCES thi_sinh(so_cccd) ON DELETE CASCADE,
    ho_so_id BIGINT REFERENCES ho_so_xet_tuyen(id) ON DELETE CASCADE,
    thu_tu_nguyen_vong INT,
    ma_truong TEXT DEFAULT 'THV',
    ma_nganh TEXT REFERENCES dm_nganh(ma_nganh),
    ten_nganh TEXT,
    ma_phuong_thuc TEXT,
    ten_phuong_thuc TEXT,
    to_hop_mon TEXT,
    trang_thai TEXT DEFAULT 'Chờ duyệt',
    ghi_chu TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Administration & CMS
CREATE TABLE quan_tri_vien (
    id SERIAL PRIMARY KEY,
    ten_dang_nhap TEXT UNIQUE NOT NULL,
    mat_khau TEXT NOT NULL,
    ho_ten TEXT NOT NULL,
    vai_tro TEXT DEFAULT 'Cán bộ xét duyệt',
    ngay_tao TIMESTAMPTZ DEFAULT NOW(),
    ngay_cap_nhat TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    summary TEXT,
    content TEXT,
    thumbnail TEXT,
    category TEXT DEFAULT 'Tin tức',
    status TEXT DEFAULT 'Draft',
    is_featured BOOLEAN DEFAULT false,
    view_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT,
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
